spring.application.name=docs-collab-service
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/docs_collab}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:huiling}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.jpa.hibernate.ddl-auto=none
spring.flyway.enabled=true